AttendanceSystem/Controllers/AttendanceController.cs
using AttendanceSystem.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Data;
using Dapper;
using System.Data.SqlClient;
using NuGet.DependencyResolver;
using NuGet.Protocol.Plugins;
using System.Runtime;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace AttendanceSystem.Controllers
{
    public class AttendanceController : Controller
    {
        private readonly string ConnectionString = "Server=.\\SQLEXPRESS; Database=AttendanceDB; User ID=your_user_id; Password=your_password; Trusted_Connection=True;MultipleActiveResultSets=true; TrustServerCertificate=true;";

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Report()
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                string sqlQuery = "SELECT ac.Id, ac.Max_punch_in_time, ac.Max_punch_out_time, emp.Id AS Employee_Id, ad.Punch_in_time, ad.Punch_out_time,emp.Name FROM AttendanceConfig ac, AttendanceDetail ad,Employee emp WHERE ac.Id = ad.Id and ad.Id=emp.Id ORDER By emp.Id ASC";
                var result = db.QueryFirstOrDefault(sqlQuery);

                int Id = result.Id;
                DateTime? PunchInTime = result.Punch_in_time;
                DateTime? PunchOutTime = result.Punch_out_time;
                DateTime? MaxPunchInTime = result.Max_punch_in_time;
                DateTime? MaxPunchOutTime = result.Max_punch_out_time;
                int Employee_Id = result.Employee_Id;
                string Name = result.Name;

                ViewBag.Id = Id;
                ViewBag.Employee_Id = Employee_Id;
                ViewBag.Name = Name;
                ViewBag.MaxPunchInTime = MaxPunchInTime;
                ViewBag.MaxPunchOutTime = MaxPunchOutTime;
                ViewBag.PunchInTime = PunchInTime;
                ViewBag.PunchOutTime = PunchOutTime;
            }
            return View("Report");
        }

        public IActionResult AdminConfigure()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AdminConfigure(DateTime MaxPunchInTime ,DateTime MaxPunchOutTime )
        {  
            DateTime MaxpunchInDateTime = MaxPunchInTime ;
            DateTime MaxpunchOutDateTime = MaxPunchOutTime;
            using IDbConnection db = new SqlConnection(ConnectionString);
            {
                string sqlQuery = "INSERT INTO AttendanceConfig (Max_punch_in_time, Max_punch_out_time) VALUES (@MaxpunchInDateTime, @MaxpunchOutDateTime)";
                db.Execute(sqlQuery, new { MaxpunchInDateTime, MaxpunchOutDateTime });
            }
                return RedirectToAction("AttendanceConfigDetails");
        }

        public IActionResult AttendanceConfigDetails()
        {
                using (IDbConnection db = new SqlConnection(ConnectionString))
                {
                    string sqlQuery = "SELECT TOP 1 Max_punch_in_time, Max_punch_out_time FROM AttendanceConfig ORDER BY Id DESC";
                    var result = db.QueryFirstOrDefault(sqlQuery);

                    DateTime MaxPunchInTime = result.Max_punch_in_time;
                    DateTime MaxPunchOutTime = result.Max_punch_out_time;

                    ViewBag.MaxPunchInTime = MaxPunchInTime;
                    ViewBag.MaxPunchOutTime = MaxPunchOutTime;

 
                    if (DateTime.Now < MaxPunchInTime && DateTime.Now > MaxPunchOutTime)
                    {
                        return RedirectToAction("EmpAbout", "Home");
                    }
                    else
                    {
                        return View();
                    }
                }
            }
 


        [HttpPost]
        public IActionResult PunchInTime()
        {
            DateTime maxPunchInTime;
            DateTime currentTime = DateTime.Now;

            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                DateTime? punchInTime = currentTime;
                string sqlQuery = "INSERT INTO AttendanceDetail (Punch_in_time) VALUES (@PunchInTime)";
                db.Execute(sqlQuery, new { PunchInTime = punchInTime });

                string query = "SELECT TOP 1 Max_punch_in_time FROM AttendanceConfig";
                var result = db.QueryFirstOrDefault(query);
                maxPunchInTime = result.Max_punch_in_time;
            }
            return RedirectToAction("Status");
        }

        [HttpPost]
        public IActionResult PunchOutTime()
        {
            DateTime maxPunchOutTime;
            DateTime currentTime = DateTime.Now;

            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                DateTime? punchOutTime = currentTime;
                string sqlQuery = "INSERT INTO AttendanceDetail (Punch_out_time) VALUES (@PunchOutTime)";
                db.Execute(sqlQuery, new { PunchOutTime=punchOutTime });

                string query = "SELECT TOP 1 Max_punch_out_time FROM AttendanceConfig ORDER BY Id DESC";
                var result = db.QueryFirstOrDefault(query);
                maxPunchOutTime = result.Max_punch_out_time;
            }
            return RedirectToAction("Status");
        }

        public IActionResult Status()
        {
            using IDbConnection db = new SqlConnection(ConnectionString);
            {
                string sqlQuery="Select Top 1 Id,Punch_in_time,Punch_out_time from AttendanceDetail order by Id desc";
                var result = db.QueryFirstOrDefault(sqlQuery);
                int Id = result.Id;
                DateTime? PunchInTime = result.Punch_in_time;
                DateTime? PunchOutTime = result.Punch_out_time;
                ViewBag.Id = Id;
                ViewBag.PunchInTime = PunchInTime;
                ViewBag.PunchOutTime = PunchOutTime;
            }
            return View("Status");
        }

        public IActionResult EarlyPunchOutReason(string reason)
        {
            using (IDbConnection db = new SqlConnection(ConnectionString))
            {
                string sqlQuery = "INSERT INTO AttendanceDetail (Early_punch_out_reason) VALUES (@Reason)";
                db.Execute(sqlQuery, new { Reason = reason });
            }
            return View("Index");
        }

        public IActionResult LatePunchInReason(string reason)
        {
                using (IDbConnection db = new SqlConnection(ConnectionString))
                {
                    string sqlQuery = "INSERT INTO AttendanceDetail (Late_punch_in_reason) VALUES (@Reason)";
                    db.Execute(sqlQuery, new { Reason = reason });
                }
                return View("Index");
        }
    }
}

AttendanceSystem/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using AttendanceSystem.Data;
using AttendanceSystem.Models;
using Microsoft.AspNetCore.Http;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using Dapper;
namespace AttendanceSystem.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly EmployeeRepository employeeRepository;
        private readonly IHttpContextAccessor? contxt;

        public EmployeesController(IHttpContextAccessor httpContextAccessor)
        {
            string connectionString = "Server=.\\SQLEXPRESS; Database=AttendanceDB; User ID=; Password=; Trusted_Connection=True; MultipleActiveResultSets=true; TrustServerCertificate=true;";
            employeeRepository = new EmployeeRepository(connectionString);
            contxt = httpContextAccessor;
        }

        // GET: Employee
        public IActionResult Index()
        {
            List<Employee> employee = employeeRepository.GetAllEmployee();
            return View(employee);
        }

        // GET: Employee/Details
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var employee = employeeRepository.GetEmployeeById(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // GET: Employee/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public IActionResult Create([Bind("Id,Name")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                bool created = employeeRepository.CreateEmployee(employee);
                if (created)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(employee);
        }

        // GET: Employee/Edit
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var employee = employeeRepository.GetEmployeeById(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employee/Edit
        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id,Name")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                bool updated = employeeRepository.UpdateEmployee(employee);

                if (updated)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(employee);
        }


        // GET: Employee/Delete
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = employeeRepository.GetEmployeeById(id);

            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employee/Delete
        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            bool deleted = employeeRepository.DeleteEmployee(id);

            if (deleted)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return NotFound();
            }
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("Username");
            return RedirectToAction("Index", "Home");
        }
    }
}

AttendanceSystem/Views/Shared/AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Attendance System</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-controller="Home" asp-action="About">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-action="Contact">Contact</a>
                </li>
            </ul>
            </nav>
    </div>
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a class="brand-link" asp-controller="Home" asp-action="About">
            <span class="brand-text font-weight-light">Amsoft Technology</span>
        </a>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon far-nav-icon"></i>
                        <p>
                            Dashboard
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Attendance" asp-action="AdminConfigure">
                                <i class="far fa-nav-icon"></i>
                                <p>Attendance Config</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Employees" asp-action="Index">
                                <i class="far fa-nav-icon"></i>
                                <p>Employee</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Attendance" asp-action="Report">
                                <i class="far fa-nav-icon"></i>
                                <p>Report</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Employees" asp-action="Logout">
                        <i class="far fa-nav-icon"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a asp-action="About" asp-controller="Home">Home</a></li>
                            <li class="breadcrumb-item active">Attendance System</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
            </div>
        </section>

        <footer class="main-footer">
            <strong></strong>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../../dist/js/adminlte.min.js"></script>
    <script src="../../dist/js/demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AttendanceSystem/Views/Shared/EmployeeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Attendance System</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="../../plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="../../dist/css/adminlte.min.css">
</head>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                    <a class="nav-link" asp-action="Contact">Contact</a>
                </li>
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Navbar Search -->
                <li class="nav-item">
                    <a class="nav-link" data-widget="navbar-search" href="#" role="button">
                        <i class="fas fa-search"></i>
                    </a>
                    <div class="navbar-search-block">
                        <form class="form-inline">
                            <div class="input-group input-group-sm">
                                <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                                <div class="input-group-append">
                                    <button class="btn btn-navbar" type="submit">
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                                        <i class="fas fa-times"></i>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </li>


                <li class="nav-item">
                    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
                        <i class="fas fa-th-large"></i>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- /.navbar -->
    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a class="brand-link" asp-controller="Home" asp-action="EmpAbout">
            <span class="brand-text font-weight-light">Amsoft Technology</span>
        </a>

        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
                     with font-awesome or any other icon font library -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon far-nav-icon"></i>
                        <p>
                            Dashboard
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Attendance" asp-action="Index">
                                <i class="far fa-nav-icon"></i>
                                <p>Attendance</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Attendance" asp-action="AttendanceConfigDetails">
                                <i class="far fa-nav-icon"></i>
                                <p>Attendance Threshold</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Attendance" asp-action="Status">
                                <i class="far fa-nav-icon"></i>
                                <p>AttendanceDetails</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Employees" asp-action="Logout">
                        <i class="far fa-nav-icon"></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <ol class="breadcrumb float-sm-right">
                            <li class="breadcrumb-item"><a href="#">Home</a></li>
                            <li class="breadcrumb-item active">Attendance System</li>
                        </ol>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
            </div>
        </section>

        <footer class="main-footer">
            <strong></strong>
        </footer>

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="../../plugins/jquery/jquery.min.js"></script>
    <script src="../../plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../../dist/js/adminlte.min.js"></script>
    <script src="../../dist/js/demo.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AttendanceSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/icheck-bootstrap/3.0.1/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <!-- /.login-logo -->
        <div class="card card-outline card-primary">
            <div class="card-header text-center">
                <h2><b>Login</b></h2>
            </div>
            <div class="card-body">
                <p class="login-box-msg">Enter your username and password</p>
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.5.0/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.1.0/js/adminlte.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>